# Generated by Django 4.2.1 on 2023-05-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_brand_category_product_brand_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered')], max_length=50, null=True),
        ),
    ]
